<?php
/**
 * Code Generator
 *
 * Generates PHP and CSS code for child theme based on configured slots.
 *
 * @package Ad_Space_Reserve
 */

if (!defined('ABSPATH')) {
    exit;
}

class ASR_Code_Generator {

    /**
     * Desktop breakpoint
     */
    const DESKTOP_BREAKPOINT = 992;

    /**
     * Default base paragraph position for infinite slots
     */
    const DEFAULT_INFINITE_BASE = 3;

    /**
     * Default spacing between infinite slots
     */
    const DEFAULT_INFINITE_SPACING = 5;

    /**
     * Generate PHP code for content injection
     *
     * @param array $slots Configured slots
     * @return string Generated PHP code
     */
    public function generate_php($slots) {
        if (empty($slots)) {
            return '';
        }

        // Group slots by device for separate injection logic
        $desktop_slots = [];
        $mobile_slots = [];

        foreach ($slots as $slot) {
            if ($slot['device'] === 'desktop') {
                $desktop_slots[] = $slot;
            } else {
                $mobile_slots[] = $slot;
            }
        }

        $php = "<?php\n";
        $php .= "/**\n";
        $php .= " * Ad Space Reserve - Generated Container Injection\n";
        $php .= " *\n";
        $php .= " * Auto-generated by Ad Space Reserve plugin.\n";
        $php .= " * Generated: " . current_time('mysql') . "\n";
        $php .= " *\n";
        $php .= " * DO NOT EDIT DIRECTLY - Changes will be overwritten.\n";
        $php .= " * Configure slots in: Settings > Ad Space Reserve\n";
        $php .= " */\n\n";

        $php .= "if (!defined('ABSPATH')) {\n";
        $php .= "    exit;\n";
        $php .= "}\n\n";

        // Main filter function
        $php .= "/**\n";
        $php .= " * Inject ad containers into content\n";
        $php .= " */\n";
        $php .= "add_filter('the_content', 'asr_inject_ad_containers', 20);\n\n";
        $php .= "function asr_inject_ad_containers(\$content) {\n";
        $php .= "    // Only run on singular posts\n";
        $php .= "    if (!is_singular() || !in_the_loop() || !is_main_query()) {\n";
        $php .= "        return \$content;\n";
        $php .= "    }\n\n";

        $php .= "    // Detect device\n";
        $php .= "    \$is_mobile = wp_is_mobile();\n\n";

        $php .= "    // Get containers based on device\n";
        $php .= "    \$containers = \$is_mobile ? asr_get_mobile_containers() : asr_get_desktop_containers();\n\n";

        $php .= "    if (empty(\$containers)) {\n";
        $php .= "        return \$content;\n";
        $php .= "    }\n\n";

        $php .= "    // Split content into paragraphs\n";
        $php .= "    \$paragraphs = preg_split('/(<\\/p>)/i', \$content, -1, PREG_SPLIT_DELIM_CAPTURE);\n";
        $php .= "    \$paragraph_count = 0;\n";
        $php .= "    \$output = '';\n";
        $php .= "    \$injected = [];\n\n";

        $php .= "    for (\$i = 0; \$i < count(\$paragraphs); \$i++) {\n";
        $php .= "        \$output .= \$paragraphs[\$i];\n\n";

        $php .= "        // Count closing paragraph tags\n";
        $php .= "        if (strtolower(\$paragraphs[\$i]) === '</p>') {\n";
        $php .= "            \$paragraph_count++;\n\n";

        $php .= "            // Check if we should inject after this paragraph\n";
        $php .= "            foreach (\$containers as \$key => \$container) {\n";
        $php .= "                if (isset(\$injected[\$key])) continue;\n\n";

        $php .= "                if (\$container['location'] === 'after_paragraph' &&\n";
        $php .= "                    \$container['position'] === \$paragraph_count) {\n";
        $php .= "                    \$output .= \"\\n\" . \$container['html'] . \"\\n\";\n";
        $php .= "                    \$injected[\$key] = true;\n";
        $php .= "                }\n";
        $php .= "            }\n";
        $php .= "        }\n";
        $php .= "    }\n\n";

        $php .= "    // Handle content_start and content_end\n";
        $php .= "    foreach (\$containers as \$key => \$container) {\n";
        $php .= "        if (isset(\$injected[\$key])) continue;\n\n";

        $php .= "        if (\$container['location'] === 'content_start') {\n";
        $php .= "            \$output = \$container['html'] . \"\\n\" . \$output;\n";
        $php .= "        } elseif (\$container['location'] === 'content_end') {\n";
        $php .= "            \$output .= \"\\n\" . \$container['html'];\n";
        $php .= "        }\n";
        $php .= "    }\n\n";

        $php .= "    return \$output;\n";
        $php .= "}\n\n";

        // Desktop containers function
        $php .= "/**\n";
        $php .= " * Get desktop ad containers\n";
        $php .= " */\n";
        $php .= "function asr_get_desktop_containers() {\n";
        $php .= "    return [\n";

        foreach ($desktop_slots as $index => $slot) {
            $php .= $this->generate_container_array($slot, $index);
        }

        $php .= "    ];\n";
        $php .= "}\n\n";

        // Mobile containers function
        $php .= "/**\n";
        $php .= " * Get mobile ad containers\n";
        $php .= " */\n";
        $php .= "function asr_get_mobile_containers() {\n";
        $php .= "    return [\n";

        foreach ($mobile_slots as $index => $slot) {
            $php .= $this->generate_container_array($slot, $index);
        }

        $php .= "    ];\n";
        $php .= "}\n";

        return $php;
    }

    /**
     * Generate container array entry for PHP
     *
     * @param array $slot Slot configuration
     * @param int $index Index for unique key
     * @return string PHP array entry
     */
    private function generate_container_array($slot, $index) {
        $cssClass = esc_attr($slot['cssClass'] ?? 'asr-ad-slot');
        $minHeight = absint($slot['minHeight'] ?? 250);
        $location = esc_attr($slot['injectionLocation'] ?? 'after_paragraph');
        $position = absint($slot['injectionPosition'] ?? 3);
        $slotType = esc_attr($slot['slotType'] ?? 'unknown');

        $html = sprintf(
            '<div class="asr-ad-slot %s" data-asr-slot="%s" style="min-height:%dpx"></div>',
            $cssClass,
            $slotType,
            $minHeight
        );

        $php = "        '{$slotType}_{$index}' => [\n";
        $php .= "            'html' => '{$html}',\n";
        $php .= "            'location' => '{$location}',\n";
        $php .= "            'position' => {$position},\n";
        $php .= "        ],\n";

        return $php;
    }

    /**
     * Generate CSS code
     *
     * @param array $slots Configured slots
     * @return string Generated CSS code
     */
    public function generate_css($slots) {
        if (empty($slots)) {
            return '';
        }

        $css = "/**\n";
        $css .= " * Ad Space Reserve - CLS Prevention Styles\n";
        $css .= " *\n";
        $css .= " * Auto-generated by Ad Space Reserve plugin.\n";
        $css .= " * Generated: " . current_time('mysql') . "\n";
        $css .= " *\n";
        $css .= " * DO NOT EDIT DIRECTLY - Changes will be overwritten.\n";
        $css .= " */\n\n";

        // Base styles for all containers
        $css .= "/* Base container styles */\n";
        $css .= ".asr-ad-slot {\n";
        $css .= "    display: block;\n";
        $css .= "    width: 100%;\n";
        $css .= "    box-sizing: border-box;\n";
        $css .= "    overflow: hidden;\n";
        $css .= "}\n\n";

        // Group by device
        $desktop_slots = [];
        $mobile_slots = [];

        foreach ($slots as $slot) {
            if ($slot['device'] === 'desktop') {
                $desktop_slots[] = $slot;
            } else {
                $mobile_slots[] = $slot;
            }
        }

        // Desktop styles
        if (!empty($desktop_slots)) {
            $css .= "/* Desktop styles (min-width: " . self::DESKTOP_BREAKPOINT . "px) */\n";
            $css .= "@media (min-width: " . self::DESKTOP_BREAKPOINT . "px) {\n";

            foreach ($desktop_slots as $slot) {
                $css .= $this->generate_slot_css($slot);
            }

            $css .= "}\n\n";
        }

        // Mobile styles
        if (!empty($mobile_slots)) {
            $css .= "/* Mobile styles (max-width: " . (self::DESKTOP_BREAKPOINT - 1) . "px) */\n";
            $css .= "@media (max-width: " . (self::DESKTOP_BREAKPOINT - 1) . "px) {\n";

            foreach ($mobile_slots as $slot) {
                $css .= $this->generate_slot_css($slot);
            }

            $css .= "}\n";
        }

        return $css;
    }

    /**
     * Generate CSS for a single slot
     *
     * @param array $slot Slot configuration
     * @return string CSS rules
     */
    private function generate_slot_css($slot) {
        $cssClass = esc_attr($slot['cssClass'] ?? 'asr-ad-slot');
        $minHeight = absint($slot['minHeight'] ?? 250);
        $marginTop = absint($slot['marginTop'] ?? 20);
        $marginBottom = absint($slot['marginBottom'] ?? 20);

        $css = "    .{$cssClass} {\n";
        $css .= "        min-height: {$minHeight}px;\n";
        $css .= "        margin-top: {$marginTop}px;\n";
        $css .= "        margin-bottom: {$marginBottom}px;\n";
        $css .= "    }\n";

        return $css;
    }

    /**
     * Generate R89 targeting instructions
     *
     * @param array $slots Configured slots
     * @return array Instructions for R89 dashboard
     */
    public function generate_r89_instructions($slots) {
        $instructions = [];

        foreach ($slots as $slot) {
            $cssClass = $slot['cssClass'] ?? 'asr-ad-slot';
            $slotType = $slot['slotType'] ?? 'unknown';
            $device = ucfirst($slot['device'] ?? 'unknown');

            $instructions[] = [
                'slot' => $slotType,
                'device' => $device,
                'selector' => '.asr-ad-slot.' . $cssClass,
                'injection' => 'inside (inject inside this container)',
            ];
        }

        return $instructions;
    }

    /**
     * Calculate spacing pattern from detected infinite slots
     *
     * Analyzes the injection positions of existing infinite/incontent slots
     * to derive the spacing pattern used by the ad network.
     *
     * @param array $slots Array of slot configurations
     * @return array ['base' => int, 'spacing' => int]
     */
    private function calculate_infinite_spacing($slots) {
        // Defensive: ensure $slots is an array
        if (!is_array($slots) || empty($slots)) {
            return [
                'base' => self::DEFAULT_INFINITE_BASE,
                'spacing' => self::DEFAULT_INFINITE_SPACING,
            ];
        }

        $positions = [];

        foreach ($slots as $slot) {
            // Defensive: ensure slot is an array
            if (!is_array($slot)) {
                continue;
            }

            $slotType = $slot['slotType'] ?? '';
            // Match infinite or incontent slot types
            if (is_string($slotType) && preg_match('/infinite|incontent/i', $slotType)) {
                $position = absint($slot['injectionPosition'] ?? 0);
                if ($position > 0) {
                    $positions[] = $position;
                }
            }
        }

        // Need at least 2 positions to calculate spacing
        if (count($positions) < 2) {
            return [
                'base' => self::DEFAULT_INFINITE_BASE,
                'spacing' => self::DEFAULT_INFINITE_SPACING,
            ];
        }

        // Sort positions to find pattern
        sort($positions);

        $base = $positions[0];
        $spacing = $positions[1] - $positions[0];

        // Ensure spacing is at least 1 and not unreasonably large
        $spacing = max(1, min(50, $spacing));

        return [
            'base' => $base,
            'spacing' => $spacing,
        ];
    }

    /**
     * Generate a placeholder infinite slot configuration
     *
     * Creates a synthetic slot configuration that continues the detected
     * spacing pattern for infinite/incontent ads.
     *
     * @param string $device 'desktop' or 'mobile'
     * @param int $index The index of this placeholder slot
     * @param array $pattern ['base' => int, 'spacing' => int]
     * @return array Slot configuration array
     */
    private function generate_placeholder_infinite_slot($device, $index, $pattern) {
        $position = $pattern['base'] + ($index * $pattern['spacing']);

        return [
            'wrapperId' => sprintf('asr-%s-infinite-%d-placeholder', $device, $index),
            'device' => $device,
            'slotType' => 'rectangle-infinite',
            'cssClass' => sprintf('asr-%s-rectangle-infinite', $device),
            'minHeight' => 250,
            'marginTop' => 20,
            'marginBottom' => 20,
            'injectionLocation' => 'after_paragraph',
            'injectionPosition' => $position,
            'enabled' => true,
            'is_placeholder' => true,
        ];
    }

    /**
     * Expand slots with placeholder infinite slots up to max setting
     *
     * This method is safe to call with any input - it will gracefully handle
     * empty arrays, malformed data, or missing settings without throwing errors.
     *
     * @param array $slots Original configured slots
     * @return array Expanded slots array (original slots returned on any error)
     */
    public function expand_infinite_slots($slots) {
        // Defensive: validate input is a non-empty array
        if (!is_array($slots) || empty($slots)) {
            return is_array($slots) ? $slots : [];
        }

        try {
            // Get max infinite slots setting with safe defaults
            $settings = get_option('asr_settings', []);
            if (!is_array($settings)) {
                $settings = [];
            }

            $max_infinite = absint($settings['max_infinite_slots'] ?? 10);

            // Clamp to reasonable range (1-50)
            $max_infinite = max(1, min(50, $max_infinite));

            // Group slots by device
            $desktop_slots = [];
            $mobile_slots = [];

            foreach ($slots as $key => $slot) {
                // Skip malformed slot entries
                if (!is_array($slot)) {
                    continue;
                }

                $device = $slot['device'] ?? 'unknown';

                if ($device === 'desktop') {
                    $desktop_slots[$key] = $slot;
                } elseif ($device === 'mobile') {
                    $mobile_slots[$key] = $slot;
                }
                // Skip slots with unknown device type
            }

            // If no valid slots found, return original
            if (empty($desktop_slots) && empty($mobile_slots)) {
                return $slots;
            }

            // Filter for infinite/incontent slots
            $infinite_pattern = '/infinite|incontent/i';

            $desktop_infinites = array_filter($desktop_slots, function($s) use ($infinite_pattern) {
                $slotType = $s['slotType'] ?? '';
                return is_string($slotType) && preg_match($infinite_pattern, $slotType);
            });

            $mobile_infinites = array_filter($mobile_slots, function($s) use ($infinite_pattern) {
                $slotType = $s['slotType'] ?? '';
                return is_string($slotType) && preg_match($infinite_pattern, $slotType);
            });

            // Calculate spacing patterns from detected slots
            $desktop_pattern = $this->calculate_infinite_spacing(array_values($desktop_slots));
            $mobile_pattern = $this->calculate_infinite_spacing(array_values($mobile_slots));

            // Generate desktop placeholders
            $desktop_infinite_count = count($desktop_infinites);
            if ($desktop_infinite_count < $max_infinite) {
                for ($i = $desktop_infinite_count; $i < $max_infinite; $i++) {
                    $placeholder = $this->generate_placeholder_infinite_slot('desktop', $i, $desktop_pattern);
                    if (is_array($placeholder) && !empty($placeholder['wrapperId'])) {
                        $desktop_slots[$placeholder['wrapperId']] = $placeholder;
                    }
                }
            }

            // Generate mobile placeholders
            $mobile_infinite_count = count($mobile_infinites);
            if ($mobile_infinite_count < $max_infinite) {
                for ($i = $mobile_infinite_count; $i < $max_infinite; $i++) {
                    $placeholder = $this->generate_placeholder_infinite_slot('mobile', $i, $mobile_pattern);
                    if (is_array($placeholder) && !empty($placeholder['wrapperId'])) {
                        $mobile_slots[$placeholder['wrapperId']] = $placeholder;
                    }
                }
            }

            // Merge back together
            return array_merge($desktop_slots, $mobile_slots);

        } catch (Exception $e) {
            // Log error for debugging but don't crash
            if (defined('WP_DEBUG') && WP_DEBUG) {
                error_log('ASR expand_infinite_slots error: ' . $e->getMessage());
            }
            // Return original slots on any error
            return $slots;
        }
    }
}
